# Generated by Django 5.0.6 on 2024-06-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='amount',
            field=models.FloatField(),
        ),
    ]
