# Generated by Django 5.0.6 on 2024-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_alter_currency_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='from_currency',
            field=models.CharField(blank=True, choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='to_currency',
            field=models.CharField(blank=True, choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, null=True, verbose_name='Currency'),
        ),
    ]
